controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

update_article_positions:
    path: '/articles/update-positions'
    controller: App\Controller\ArticleController::updatePositions'
    methods: ['POST']
